name = pw_tests
title = PerfectWorld Tests
description = Tests for PerfectWorld using Luanti TestKit
author = mirivlad
depends = luanti_testkit, pw_core, pw_planner, pw_structures, pw_compat_mcl
optional_depends = pw_debug
