server_name = PerfectWorld Dev
server_description = PerfectWorld on Luanti/Mineclonia.
motd = Welcome to PerfectWorld dev server.
enable_server = true
creative_mode = true
enable_damage = false
default_privs = interact, shout, fly, fast, noclip, server
max_users = 10
strict_protocol_version_checking = false
